apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite
        image: anas025/for-docker-app:prod-${BUILD_NUMBER}  # Jenkins pipeline se replace hoga
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
